// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmplegkwzvddvkumikxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtcGxlZ2t3enZkZHZrdW1pa3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwODU4OTYsImV4cCI6MjA5MzY2MTg5Nn0.SUoTvJa2NZ62VrqYHWGJ0AZYMtplgPFhV8e_M7wC8JI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});